# Site settings
title: Luna Kang
description: |
  Let's Build Something<br>Special Together
owner: Luna Kang
first_published: 2017
email: #Full email address
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://lkang-pdx.github.io" # the base hostname & protocol for your site
social:
  github: https://github.com/lkang-pdx
  linkedin-square: https://linkedin.com/in/lunakang
  twitter: https://twitter.com/TheLunaKang
  #facebook-official: https://facebook.com/<username>
  #google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Scripts
google_analytics: "UA-87672791-1"

# Build settings
markdown: kramdown
#sass:
#  style: compressed
